/* The following code was generated by JFlex 1.4.3 on 31-05-21 06:25 PM */

package analizadorLexico;
import static analizadorLexico.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 31-05-21 06:25 PM from the specification file
 * <tt>E:/UPB/7moSemestre/Compilacion/ProyectoFinal/AnalizadorLexico/JavaAnalizadorLexico/src/analizadorLexico/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\26\1\25\2\0\1\6\22\0\1\6\1\46\1\32\1\31"+
    "\2\0\1\33\1\0\1\41\1\42\1\30\1\2\1\6\1\3\1\5"+
    "\1\24\12\4\3\0\1\27\3\0\32\1\4\0\1\1\1\0\1\11"+
    "\1\23\1\45\1\37\1\17\1\35\1\22\1\1\1\10\2\1\1\12"+
    "\1\20\1\21\1\15\1\16\1\1\1\14\1\7\1\13\1\36\1\40"+
    "\4\1\1\43\1\34\1\44\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\7\2"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\2\1"+
    "\4\2\1\16\1\17\1\20\1\21\1\1\1\0\1\2"+
    "\1\1\2\0\1\22\1\23\11\2\1\6\1\24\4\2"+
    "\1\0\1\1\1\0\1\1\1\5\1\25\6\2\1\26"+
    "\7\2\4\0\1\25\10\2\1\27\3\2\1\30\2\0"+
    "\1\5\1\1\2\0\2\2\1\31\1\32\3\2\1\33"+
    "\2\2\2\0\1\25\1\2\1\34\2\2\1\35\1\36"+
    "\1\2\2\0\2\25\1\37\2\2\1\0\1\2\1\36"+
    "\1\2\1\36\1\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\165\0\234\0\303\0\352"+
    "\0\u0111\0\u0138\0\u015f\0\u0186\0\u01ad\0\u01d4\0\u01fb\0\47"+
    "\0\47\0\47\0\47\0\47\0\47\0\u0222\0\u0249\0\u0270"+
    "\0\u0297\0\u02be\0\u02e5\0\u030c\0\47\0\47\0\47\0\u0333"+
    "\0\u035a\0\u0381\0\u03a8\0\u03cf\0\u03f6\0\47\0\116\0\u041d"+
    "\0\u0444\0\u046b\0\u0492\0\u04b9\0\u04e0\0\u0507\0\u052e\0\u0555"+
    "\0\u057c\0\47\0\u05a3\0\u05ca\0\u05f1\0\u0618\0\u063f\0\u0666"+
    "\0\u068d\0\u06b4\0\u06db\0\u0702\0\u0729\0\u0750\0\u0777\0\u079e"+
    "\0\u07c5\0\u07ec\0\116\0\u0813\0\u083a\0\u0861\0\u0888\0\u08af"+
    "\0\u08d6\0\u08fd\0\u0924\0\u094b\0\u0972\0\u0999\0\u09c0\0\u09e7"+
    "\0\u0a0e\0\u0a35\0\u0a5c\0\u0a83\0\u0aaa\0\u0ad1\0\u0af8\0\116"+
    "\0\u0b1f\0\u0b46\0\u0b6d\0\116\0\u0b94\0\u0bbb\0\47\0\u0be2"+
    "\0\u0c09\0\u0c30\0\u0c57\0\u0c7e\0\116\0\116\0\u0ca5\0\u0ccc"+
    "\0\u0cf3\0\116\0\u0d1a\0\u0d41\0\u0d68\0\u0d8f\0\u0db6\0\u0ddd"+
    "\0\116\0\u0e04\0\u0e2b\0\116\0\116\0\u0e52\0\u0e79\0\u0ea0"+
    "\0\47\0\u0ec7\0\116\0\u0eee\0\u0f15\0\u0f3c\0\u0f63\0\u0f8a"+
    "\0\u0fb1\0\47\0\116";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\2\1\7\1\10"+
    "\1\11\1\12\2\3\1\13\1\3\1\14\1\3\1\15"+
    "\2\3\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\3\1\40\50\0\1\3\2\41"+
    "\1\42\2\0\15\3\11\0\4\3\4\0\1\3\1\2"+
    "\4\0\1\6\43\0\1\43\2\44\1\6\1\45\1\0"+
    "\15\43\11\0\4\43\4\0\1\43\1\46\6\0\1\7"+
    "\41\0\1\3\2\41\1\42\2\0\1\3\1\47\2\3"+
    "\1\50\10\3\11\0\4\3\4\0\1\3\1\2\1\0"+
    "\1\3\2\41\1\42\2\0\12\3\1\51\2\3\11\0"+
    "\4\3\4\0\1\3\1\2\1\0\1\3\2\41\1\42"+
    "\2\0\3\3\1\52\11\3\11\0\4\3\4\0\1\3"+
    "\1\2\1\0\1\3\2\41\1\42\2\0\10\3\1\53"+
    "\4\3\11\0\4\3\4\0\1\3\1\2\1\0\1\3"+
    "\2\41\1\42\2\0\5\3\1\54\2\3\1\55\4\3"+
    "\11\0\4\3\4\0\1\3\1\2\1\0\1\3\2\41"+
    "\1\42\2\0\2\3\1\56\5\3\1\57\4\3\11\0"+
    "\4\3\4\0\1\3\1\2\1\0\1\3\2\41\1\42"+
    "\2\0\6\3\1\60\6\3\11\0\4\3\4\0\1\3"+
    "\1\2\24\0\1\61\55\0\1\62\47\0\1\62\13\0"+
    "\1\3\2\41\1\42\2\0\2\3\1\63\12\3\11\0"+
    "\4\3\4\0\1\3\1\2\1\0\1\3\2\41\1\42"+
    "\2\0\13\3\1\64\1\3\11\0\4\3\4\0\1\3"+
    "\1\2\1\0\1\3\2\41\1\42\2\0\1\3\1\65"+
    "\13\3\11\0\4\3\4\0\1\3\1\2\1\0\1\3"+
    "\2\41\1\42\2\0\10\3\1\66\4\3\11\0\4\3"+
    "\4\0\1\3\1\2\3\0\1\67\44\0\1\70\2\71"+
    "\1\72\2\0\15\70\11\0\4\70\4\0\1\70\5\0"+
    "\1\42\43\0\1\42\2\41\1\42\2\0\15\42\11\0"+
    "\4\42\4\0\1\42\2\0\1\43\2\71\1\72\2\0"+
    "\15\43\11\0\4\43\4\0\1\43\5\0\1\73\46\0"+
    "\1\74\43\0\1\3\2\41\1\42\2\0\5\3\1\75"+
    "\7\3\11\0\4\3\4\0\1\3\1\2\1\0\1\3"+
    "\2\41\1\42\2\0\4\3\1\76\10\3\11\0\1\77"+
    "\3\3\4\0\1\3\1\2\1\0\1\3\2\41\1\42"+
    "\2\0\4\3\1\100\10\3\11\0\4\3\4\0\1\3"+
    "\1\2\1\0\1\3\2\41\1\42\2\0\2\3\1\101"+
    "\12\3\11\0\4\3\4\0\1\3\1\2\1\0\1\3"+
    "\2\41\1\42\2\0\1\3\1\102\13\3\11\0\4\3"+
    "\4\0\1\3\1\2\1\0\1\3\2\41\1\42\2\0"+
    "\5\3\1\103\7\3\11\0\4\3\4\0\1\3\1\2"+
    "\1\0\1\3\2\41\1\42\2\0\13\3\1\104\1\3"+
    "\11\0\4\3\4\0\1\3\1\2\1\0\1\3\2\41"+
    "\1\42\2\0\12\3\1\105\2\3\11\0\4\3\4\0"+
    "\1\3\1\2\1\0\1\3\2\41\1\42\2\0\6\3"+
    "\1\106\6\3\11\0\4\3\4\0\1\3\1\2\25\61"+
    "\1\0\21\61\1\0\1\3\2\41\1\42\2\0\3\3"+
    "\1\107\11\3\11\0\4\3\4\0\1\3\1\2\1\0"+
    "\1\3\2\41\1\42\2\0\15\3\11\0\1\3\1\110"+
    "\2\3\4\0\1\3\1\2\1\0\1\3\2\41\1\42"+
    "\2\0\15\3\11\0\3\3\1\111\4\0\1\3\1\2"+
    "\1\0\1\3\2\41\1\42\2\0\5\3\1\112\7\3"+
    "\11\0\4\3\4\0\1\3\1\2\2\0\2\113\1\114"+
    "\43\0\1\70\5\0\15\70\11\0\4\70\4\0\1\70"+
    "\5\0\1\72\44\0\2\71\1\72\1\115\43\0\2\44"+
    "\1\73\43\0\1\43\2\116\1\117\2\0\15\43\11\0"+
    "\4\43\4\0\1\43\2\0\1\3\2\41\1\42\2\0"+
    "\1\3\1\120\13\3\11\0\4\3\4\0\1\3\1\2"+
    "\1\0\1\3\2\41\1\42\2\0\10\3\1\121\4\3"+
    "\11\0\4\3\4\0\1\3\1\2\1\0\1\3\2\41"+
    "\1\42\2\0\10\3\1\122\4\3\11\0\4\3\4\0"+
    "\1\3\1\2\1\0\1\3\2\41\1\42\2\0\5\3"+
    "\1\123\7\3\11\0\4\3\4\0\1\3\1\2\1\0"+
    "\1\3\2\41\1\42\2\0\3\3\1\124\11\3\11\0"+
    "\4\3\4\0\1\3\1\2\1\0\1\3\2\41\1\42"+
    "\2\0\12\3\1\125\2\3\11\0\4\3\4\0\1\3"+
    "\1\2\1\0\1\3\2\41\1\42\2\0\13\3\1\126"+
    "\1\3\11\0\4\3\4\0\1\3\1\2\1\0\1\3"+
    "\2\41\1\42\2\0\4\3\1\127\10\3\11\0\4\3"+
    "\4\0\1\3\1\2\1\0\1\3\2\41\1\42\2\0"+
    "\3\3\1\130\11\3\11\0\4\3\4\0\1\3\1\2"+
    "\1\0\1\3\2\41\1\42\2\0\1\131\14\3\11\0"+
    "\4\3\4\0\1\3\1\2\1\0\1\3\2\41\1\42"+
    "\2\0\2\3\1\132\12\3\11\0\4\3\4\0\1\3"+
    "\1\2\1\0\1\3\2\41\1\42\2\0\10\3\1\133"+
    "\4\3\11\0\4\3\4\0\1\3\1\2\1\0\1\3"+
    "\2\41\1\42\2\0\6\3\1\134\6\3\11\0\4\3"+
    "\4\0\1\3\1\2\4\0\1\114\44\0\2\135\1\114"+
    "\1\136\34\0\1\137\10\0\1\140\46\0\1\141\43\0"+
    "\1\43\2\116\1\117\1\142\1\0\15\43\11\0\4\43"+
    "\4\0\1\43\2\0\1\3\2\41\1\42\2\0\12\3"+
    "\1\143\2\3\11\0\4\3\4\0\1\3\1\2\1\0"+
    "\1\3\2\41\1\42\2\0\5\3\1\144\7\3\11\0"+
    "\4\3\4\0\1\3\1\2\1\0\1\3\2\41\1\42"+
    "\2\0\5\3\1\126\7\3\11\0\4\3\4\0\1\3"+
    "\1\2\1\0\1\3\2\41\1\42\2\0\6\3\1\145"+
    "\6\3\11\0\4\3\4\0\1\3\1\2\1\0\1\3"+
    "\2\41\1\42\2\0\10\3\1\146\4\3\11\0\4\3"+
    "\4\0\1\3\1\2\1\0\1\3\2\41\1\42\2\0"+
    "\15\3\11\0\4\3\4\0\1\147\1\2\1\0\1\3"+
    "\2\41\1\42\2\0\1\3\1\150\13\3\11\0\4\3"+
    "\4\0\1\3\1\2\1\0\1\3\2\41\1\42\2\0"+
    "\5\3\1\151\7\3\11\0\4\3\4\0\1\3\1\2"+
    "\1\0\1\3\2\41\1\42\2\0\6\3\1\152\6\3"+
    "\11\0\4\3\4\0\1\3\1\2\1\0\1\3\2\41"+
    "\1\42\2\0\3\3\1\153\11\3\11\0\4\3\4\0"+
    "\1\3\1\2\1\0\1\3\2\41\1\42\2\0\5\3"+
    "\1\154\7\3\11\0\4\3\4\0\1\3\1\2\4\0"+
    "\1\155\46\0\1\156\44\0\2\71\1\72\46\0\1\141"+
    "\1\142\45\0\1\157\43\0\1\3\2\41\1\42\2\0"+
    "\13\3\1\160\1\3\11\0\4\3\4\0\1\3\1\2"+
    "\1\0\1\3\2\41\1\42\2\0\6\3\1\161\6\3"+
    "\11\0\4\3\4\0\1\3\1\2\1\0\1\3\2\41"+
    "\1\42\2\0\1\3\1\162\13\3\11\0\4\3\4\0"+
    "\1\3\1\2\1\0\1\3\2\41\1\42\2\0\6\3"+
    "\1\163\6\3\11\0\4\3\4\0\1\3\1\2\1\0"+
    "\1\3\2\41\1\42\2\0\10\3\1\164\4\3\11\0"+
    "\4\3\4\0\1\3\1\2\1\0\1\3\2\41\1\42"+
    "\2\0\10\3\1\165\4\3\11\0\4\3\4\0\1\3"+
    "\1\2\1\0\1\3\2\41\1\42\2\0\1\166\14\3"+
    "\11\0\4\3\4\0\1\3\1\2\2\0\2\135\1\155"+
    "\35\0\1\137\6\0\2\167\1\170\35\0\1\171\6\0"+
    "\2\116\1\172\43\0\1\3\2\41\1\42\2\0\2\3"+
    "\1\173\12\3\11\0\4\3\4\0\1\3\1\2\1\0"+
    "\1\3\2\41\1\42\2\0\7\3\1\174\5\3\11\0"+
    "\4\3\4\0\1\3\1\2\1\0\1\3\2\41\1\42"+
    "\2\0\5\3\1\175\7\3\11\0\4\3\4\0\1\3"+
    "\1\2\1\0\1\3\2\41\1\42\2\0\6\3\1\165"+
    "\6\3\11\0\4\3\4\0\1\3\1\2\4\0\1\176"+
    "\44\0\2\167\1\170\1\136\34\0\1\171\6\0\2\116"+
    "\1\172\1\142\42\0\1\3\2\41\1\42\2\0\2\3"+
    "\1\177\12\3\11\0\4\3\4\0\1\3\1\2\1\0"+
    "\1\3\2\41\1\42\2\0\10\3\1\200\4\3\11\0"+
    "\4\3\4\0\1\3\1\2\4\0\1\176\1\136\42\0"+
    "\1\3\2\41\1\42\2\0\3\3\1\201\11\3\11\0"+
    "\4\3\4\0\1\3\1\2\1\0\1\3\2\41\1\42"+
    "\2\0\15\3\3\0\1\202\5\0\4\3\4\0\1\3"+
    "\1\2\1\0\1\3\2\41\1\42\2\0\10\3\1\203"+
    "\4\3\11\0\4\3\4\0\1\3\1\2";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4056];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\15\1\6\11\7\1\3\11\1\1\1\0"+
    "\2\1\2\0\1\11\13\1\1\11\4\1\1\0\1\1"+
    "\1\0\21\1\4\0\16\1\2\0\1\11\1\1\2\0"+
    "\12\1\2\0\10\1\2\0\1\11\4\1\1\0\3\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 110) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 27: 
          { lexeme = yytext(); return Logico_false;
          }
        case 33: break;
        case 31: 
          { lexeme=yytext(); return Reservada_string;
          }
        case 34: break;
        case 23: 
          { lexeme=yytext(); return Reservada_boolean;
          }
        case 35: break;
        case 21: 
          { lexeme=yytext(); return NumeroReal;
          }
        case 36: break;
        case 3: 
          { lexeme=yytext(); return suma;
          }
        case 37: break;
        case 26: 
          { lexeme=yytext(); return Reservada_float;
          }
        case 38: break;
        case 4: 
          { lexeme=yytext(); return resta;
          }
        case 39: break;
        case 30: 
          { lexeme = yytext(); return Op_relacional;
          }
        case 40: break;
        case 22: 
          { lexeme=yytext(); return Reservada_for;
          }
        case 41: break;
        case 7: 
          { lexeme=yytext(); return division;
          }
        case 42: break;
        case 9: 
          { lexeme=yytext(); return Tabulacion;
          }
        case 43: break;
        case 25: 
          { lexeme=yytext(); return Reservada_else;
          }
        case 44: break;
        case 1: 
          { lexeme=yytext(); return ERROR_LÉXICO;
          }
        case 45: break;
        case 8: 
          { lexeme=yytext(); return SaltoLinea;
          }
        case 46: break;
        case 18: 
          { lexeme=yytext(); return Factorial;
          }
        case 47: break;
        case 16: 
          { lexeme=yytext(); return Llave_abrir;
          }
        case 48: break;
        case 5: 
          { lexeme=yytext(); return Numero;
          }
        case 49: break;
        case 11: 
          { lexeme=yytext(); return multiplicacion;
          }
        case 50: break;
        case 10: 
          { lexeme=yytext(); return igual;
          }
        case 51: break;
        case 19: 
          { lexeme=yytext(); return Reservada_if;
          }
        case 52: break;
        case 2: 
          { lexeme=yytext(); return Identificador;
          }
        case 53: break;
        case 12: 
          { lexeme=yytext(); return fin_de_linea;
          }
        case 54: break;
        case 17: 
          { lexeme=yytext(); return Llave_cerrar;
          }
        case 55: break;
        case 28: 
          { lexeme=yytext(); return Reservada_int;
          }
        case 56: break;
        case 32: 
          { lexeme=yytext(); return Main;
          }
        case 57: break;
        case 15: 
          { lexeme=yytext(); return Parentesis_cerrar;
          }
        case 58: break;
        case 29: 
          { lexeme=yytext(); return Reservada_while;
          }
        case 59: break;
        case 24: 
          { lexeme = yytext(); return Logico_true;
          }
        case 60: break;
        case 6: 
          { /*Ignore*/
          }
        case 61: break;
        case 20: 
          { lexeme=yytext(); return Op_logico;
          }
        case 62: break;
        case 13: 
          { lexeme=yytext(); return comillas;
          }
        case 63: break;
        case 14: 
          { lexeme=yytext(); return Parentesis_abrir;
          }
        case 64: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
